### ISSUE TITLE
Edit our full stack page to include feedback from reviewers

### ISSUE THREAD

**Issue by MichaelKentBurns** [MichaelKentBurns/MichaelKentBurns.com#19]
We received reviews from all 3 first reviewers.  I'll include them in this discussion.
This page is a bit tricky since it is an umbrella over front end and back end issues.  
We don't want to duplicate material, so this page can't be written fully until the other two are finished and approved.

**Comment by MichaelKentBurns** [comment]
Efatha's review from an email April 3rd:  

> Comments
In the full stack skills wikipedia have different meanings on the frontend and backend link, which is not bad though. But one thing more interesting is the terms frontend and backend in software engineering,
that refer to the [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) between the [presentation layer](https://en.wikipedia.org/wiki/Presentation_layer) (frontend), and the [data access layer](https://en.wikipedia.org/wiki/Data_access_layer) (backend) of a piece of [software](https://en.wikipedia.org/wiki/Software).  This page is meaningful, saying that the full stack includes both front end and back end skills.
questions
1.What is the main role of a full stack developer in the group of other developers?
2.Do we really need a full stack developer in a larger project which has both front end and back end developers?
3.What are the advantages of being a full stack developer?
4.how does wordpress work?
recommendations
 Best Practices for Full Stack Development

Here are some best practices for full-stack development that can help you build better applications.

Plan Before You Start
Before you start coding, it’s essential to plan out your application. Determine the features that your application will have, and then break them down into smaller tasks. This will help you to have a clear idea of what you need to accomplish and what technologies you’ll need to use.

2. Follow the Best Practices for Coding

Follow best practices for coding, such as using proper naming conventions, writing clean and concise code, and using comments to explain your code. Using version control systems like Git and following Agile methodologies can also help you to stay organized and on track.

3. Document your Code

Documenting your code is important for future developers who may need to work on your application. It also helps you to remember what you did and why you did it. Use comments and documentation tools like JSDoc to document your code.

4. Use Continuous Integration and Continuous Deployment (CI/CD)

Continuous Integration and Continuous Deployment (CI/CD) can help you to streamline your development process and release updates more quickly. CI/CD involves automating the build, testing, and deployment of your application. Use tools like Jenkins, Travis CI, or CircleCI to set up your CI/CD pipeline.

5. Focus on User Experience

The user experience is crucial for the success of your application. Keep your users in mind when designing your application and focus on providing a user-friendly and intuitive interface. Conduct user testing and gather feedback to continuously improve the user experience.

[The strategies to learn full stack](https://medium.com/@TusharKanjariya/best-practices-for-full-stack-development-strategies-for-success-2130a0aab4be#:~:text=%F0%9F%91%89-,Best%20Practices%20for%20Full%20Stack%20Development,to%20monitor%20your%20application%E2%80%99s%20performance%20and%20gather%20insights%20into%20user%20behavior.,-Get%20an%20email)

👉 Strategies for Success in Full Stack Development

To be successful in full stack development, there are several strategies that you should follow:

Learn both front-end and back-end technologies
To be a successful full stack developer, it is essential to have a strong foundation in both front-end and back-end development. This will allow you to create applications that are not only functional but also scalable and maintainable.

2. Stay up-to-date with new technologies

Technology is constantly evolving, and it is important to stay up-to-date with the latest trends and technologies. This will allow you to create applications that are not only functional but also innovative and cutting-edge.

3. Focus on User Experience

User experience is essential for creating applications that are not only functional but also user-friendly. By focusing on user experience, you can create applications that are easy to use and navigate, which will ultimately lead to higher user engagement and satisfaction.

4. Collaborate with other developers

Collaborating with other developers is essential for learning new skills and approaches, as well as for sharing knowledge and expertise. By collaborating with other developers, you can learn from their experiences and improve your own skills and knowledge.

5. Use Analytics and Monitoring

Analytics and monitoring can help you to understand how your application is being used and identify any issues or bottlenecks.

Use tools like [Google Analytics](https://analytics.google.com/), [New Relic](https://newrelic.com/), or [AppDynamics](https://www.appdynamics.com/) to monitor your application’s performance and gather insights into user behavior.

This is a good way to learn full stack development skills.

[more to learn about full stack](https://www.freecodecamp.org/news/learn-full-stack-development-html-css-javascript-node-js-mongodb/#:~:text=Learn%20Full%20Stack%20Development)

**Comment by MichaelKentBurns** [comment]
Ash's review received in email March 21st:

> Hello Michael,

This page provides a brief overview of full-stack development, highlighting the integration of front-end and back-end skills, as well as deployment and configuration considerations. Here are some feedback and suggestions:

Clear Explanation: The explanation of full-stack development is concise and easy to understand, which is helpful for beginners. The text effectively conveys the idea that full-stack development encompasses both front-end and back-end skills, as well as deployment considerations.
Practical Example: Describing your own experience with hosting WordPress sites on Cloudways VPS adds a personal touch and makes the concept of full-stack development more relatable. It provides readers with a real-world example of how full-stack skills are applied in practice.
Emphasis on WordPress: While WordPress is a popular platform and a valid choice for full-stack development, it's important to note that full-stack developers can work with a variety of technologies and frameworks, depending on project requirements. Mentioning other options for back-end development, such as Node.js, Django, or Ruby on Rails, to provide readers with a broader perspective.
Training Opportunity: Highlighting the opportunity for new developers to gain experience by contributing to the development of your WordPress site is a valuable point. It demonstrates the collaborative nature of full-stack development and the importance of hands-on experience in learning.
Diversification of Skills: Encourage readers to explore a range of technologies and frameworks beyond WordPress. While WordPress is a versatile platform, having knowledge of multiple technologies allows developers to adapt to different project requirements and stay competitive in the job market.
Integration of Frontend and Backend: Emphasize the importance of seamless integration between the front end and back end in full-stack development. Discuss common techniques for communication between the two layers, such as RESTful APIs or GraphQL, to give readers a deeper understanding of how full-stack applications are structured.
Resource Recommendations: Provide links to additional resources where readers can learn more about full-stack development, including tutorials, online courses, and community forums.
Mentioning specific resources tailored to full-stack development would be beneficial for readers looking to further their skills in this area.

Thank you!

**Comment by MichaelKentBurns** [comment]
Philemon's review (email March 20, 3:08 PM) includes another roadmap that should be added to our site and his contribution page:

> Hi Michael,
I've just been through the full stack web section of the site and I find it very interesting; I'd like us to be able to help new learners with a resource containing a roadmap or practical guide giving them the steps to follow in their apprenticeship to become a full stack web developer. To do this, I suggest inserting a link at the end of the page to a PDF document containing the roadmap in question, which they can download, or asking them for their e-mail address so that it can be sent to their inbox.

Here's an example of the roadmap in question:


Your Journey to Full-Stack Mastery: A Comprehensive Roadmap

The world of web development is vast and ever-evolving. Full-stack developers, the wizards behind both the user-facing interfaces and the server-side magic that powers them, are in high demand. But where do you begin on this exciting path? Don't worry, aspiring developer, this roadmap will guide you step-by-step towards becoming a well-rounded full-stack developer.

Phase 1: Building the Foundation

Master the Fundamentals: Before diving into code, solidify your understanding of core web development concepts like HTML, CSS, and JavaScript. HTML structures web pages, CSS styles them, and JavaScript brings interactivity. Numerous online resources and interactive tutorials can get you started.
Command the Browser: Learn how web browsers work and how they interpret your code. Familiarize yourself with the Document Object Model (DOM) and how JavaScript interacts with it.
Phase 2: Front-End Development

Deepen Your JavaScript Expertise: Move beyond the basics and explore advanced JavaScript concepts like object-oriented programming, closures, and asynchronous programming. This empowers you to build complex user interfaces with dynamic behavior.
Embrace Front-End Frameworks: Popular frameworks like React, Angular, or Vue.js streamline front-end development. These tools offer pre-built components and functionalities, allowing you to focus on creating awesome user experiences.
Learn CSS Preprocessors: Level up your CSS with preprocessors like Sass or LESS. These tools offer features like variables, mixins, and nesting, making your stylesheets more maintainable and scalable.
Phase 3: Back-End Development

Choose a Back-End Language: Pick a server-side language like Python, Node.js (JavaScript on the server-side!), Java, or PHP. Each offers its strengths and weaknesses, so research which aligns with your interests and potential projects.
Dive into Databases: Websites often need to store data. Learn about relational databases like MySQL or PostgreSQL and explore NoSQL databases like MongoDB for specific use cases. Understand how to interact with databases from your back-end code.
Server-Side Development Fundamentals: Grasp core back-end concepts like APIs (Application Programming Interfaces), which allow different parts of your application to communicate. Learn how to build APIs using your chosen back-end language and framework.
Phase 4: Putting it All Together

Full-Stack Frameworks: Some frameworks like Ruby on Rails (using Ruby) or Django (using Python) offer a full-stack solution, simplifying the integration between front-end and back-end development. Consider exploring these if you prefer a more streamlined approach.
Version Control with Git: Learn Git, a version control system, to track changes in your codebase and collaborate effectively with others. This is crucial for any serious developer.
Build Projects: Now that you possess the building blocks, put your skills to the test! Start with small personal projects and gradually build more complex applications. This practical experience solidifies your learnings and builds your portfolio.
Phase 5: Continuous Learning

The world of web development is constantly evolving. Stay updated with the latest trends and technologies. Explore new frameworks, libraries, and best practices through online courses, articles, and developer communities.

Best regards

Bahati

**Comment by MichaelKentBurns** [comment]
Upwork job posted and job accepted by Ash.

**Comment by AshDest** [comment]
I made changes to the Full Stack page based on your comments. you will see that I did not do in-depth details since most of the content should be in the [Frontend](https://michaelkentburns.com/index.php/front-end-web) and [Backend](https://michaelkentburns.com/index.php/back-end-web) page.
https://michaelkentburns.com/index.php/full-stack/

**Comment by AshDest** [comment]
please @bahati7, @efatha, you can check the page and tell me if the changes were made according to your comments

**Comment by MichaelKentBurns** [comment]
Here are Michael's first review questions and comments: 
Overall, this is a valuable addition to my admittedly scant page.  Well done.  

1.  First paragraph: "where a single developer works on both the front-end and back-end aspects."  I think this is a single developer only situation.  Very often there are several developers who cooperate on these projects.  For a good example, the next project I have for you three is a full stack and will require contributions from all three of you individually and coordination as a team under a team lead.    I suggest changing that quoted phrase to something like "that involve front-end, back-end, and stack deployment and management."  Yes, there are "full stack developers" that can do it all, but teams are often used.  It's OK to mention full stack developer individuals, but it should be clear that teams are probably more common.
2. I like the graphic, but wonder about its source.  Did you create that or was it from another site.  If from another site, did you check the copyright policy for that site?  Many sites allow copying (with some restrictions) and some copyright the whole site and thus, we cannot use it.  We must then create our own graphic or find one that is public domain (see https://commons.wikimedia.org/wiki/Main_Page)
3. The paragraph on frameworks would be more readable as a list and should have a prominent header.  You might also introduce that with a short explanation of what a framework is.  There is a good wikipedia page 'Software framework' that you should link for more information. 
4. The mention of 'cloud platforms' should be its own section with a header. 
5. The paragraph starting "This WordPress site" is duplicated.  Coming after your good discussion of frameworks,  you should perhaps have a header like 'WordPress as a full stack platform'. 
6. The last paragraph seems out of context,  it should be included at the end of the section on 'full stack developer' mentioned in my first point.  

Finally, you have my permission to add a note at the bottom where you take credit for authoring this page, with a link to your contributions page.   You should also take over your contributions page and make it your own.   Feel free to include a short bio and/or links to your portfolio page and/or Upwork profile.

**Comment by MichaelKentBurns** [comment]
One more comment.  In the section on an individual full stack developer, you might suggest some advice or pointers for developers who are not to that skill level as to how to develop themselves to get to the goal.  Are there any training sites that will lead them on their journey?

**Comment by bahati7** [comment]
> please @bahati7, @efatha, you can check the page and tell me if the changes were made according to your comments

The work is well done, I would only suggest adding some sort of roadmap or some resources to guide someone who wants to start their career as a fullstak developer.

**Comment by efatha** [comment]
> please @bahati7, @efatha, you can check the page and tell me if the changes were made according to your comments

Yes, I did visit the website. It's awesome, I validate the full-stack's page. More explanation, deep meanings and good information!

**Comment by AshDest** [comment]
Feed back about Michael's first review questions and comments: 
>First paragraph: "where a single developer works on both the front-end and back-end aspects." I think this is a single developer only situation. Very often there are several developers who cooperate on these projects. For a good example, the next project I have for you three is a full stack and will require contributions from all three of you individually and coordination as a team under a team lead. I suggest changing that quoted phrase to something like "that involve front-end, back-end, and stack deployment and management." Yes, there are "full stack developers" that can do it all, but teams are often used. It's OK to mention full stack developer individuals, but it should be clear that teams are probably more common.

>I like the graphic, but wonder about its source. Did you create that or was it from another site. If from another site, did you check the copyright policy for that site? Many sites allow copying (with some restrictions) and some copyright the whole site and thus, we cannot use it. We must then create our own graphic or find one that is public domain (see https://commons.wikimedia.org/wiki/Main_Page)

>The paragraph on frameworks would be more readable as a list and should have a prominent header. You might also introduce that with a short explanation of what a framework is. There is a good wikipedia page 'Software framework' that you should link for more information.

>The mention of 'cloud platforms' should be its own section with a header.

>The paragraph starting "This WordPress site" is duplicated. Coming after your good discussion of frameworks, you should perhaps have a header like 'WordPress as a full stack platform'.
The last paragraph seems out of context, it should be included at the end of the section on 'full stack developer' mentioned in my first point.

I have made the modifications according to all these comments.
Regarding the graphic image, I have designed a new image to illustrate the context of a full-stack developer.

**Comment by MichaelKentBurns** [comment]
Much better, thanks. 
Just a few trivial details.

The title on the graphic has a double P in DEVELOPMENT.
There are a few places where you use the term framework in a plural sense and so it needs an 's' on the end.
For example 'Some framework' should be 'Some frameworks'
Also 'More about frameworks', 'there are many frameworks like:' 

Finally, I think there should be some suggestions about where to gain the skills for a full stack developer.  I think it should go right after the sentence 'It will require you to learn a lot of different skills, but it can be a very rewarding career path.' 

A quick google of 'training site for full stack developers' shows several suggestions that I'm not qualified to comment on.  Maybe you know, or we could simply point them to that search and let them decide.   

All in all, I think we have a nice page now.  Certainly better than my effort.   Thank you.

**Comment by AshDest** [comment]
Hello Michael, I applied some suggestions you gave, and also made some additions to illustrate some learning platforms

**Comment by AshDest** [comment]
@bahati7 
>The work is well done, I would only suggest adding some sort of roadmap or some resources to guide someone who wants to start their career as a fullstak developer.

I did not add sort of roadmap because I think that the Frontend and Backend page should offer this. It's part of the full-stack development process.
but I added the resource references.

![image](https://github.com/MichaelKentBurns/MichaelKentBurns.com/assets/51165519/30399f68-1431-48fc-87a0-f1d7d4b28add)

**Comment by MichaelKentBurns** [comment]
All this looks great!    
This page is very much improved. 
Thanks for your significant efforts and knowledge.
